### ISSUE TITLE
Nat ADT

### ISSUE THREAD

**Issue by altaic** [JoeyEremondi/elm-typenats#1]
Wouldn't the following be better at representing natural numbers in the type system?

```
type Nat
  = Zero
  | OnePlus Nat
```

That way, you don't have to worry about telling people "please only give another TypeNat as the argument to OnePlus."

**Comment by JoeyEremondi** [comment]
Nope, the point of the library is to represent natural numbers at a Type
level. Your system allows you to define value-level Nats, but not
type-level.

For example, in my SafeList library, you can do "Safe a Zero" for a list
with 0 elements. But in your system, we get the following error: "Cannot
find type `Zero`". Because Zero isn't a type, it's a data constructor.

Haskell lets you get away with things like you have, using the DataKinds
extension, but in Elm we have no such luck.

**Comment by altaic** [comment]
Ah, I see what you mean. Thanks for the explanation.
